[project]
name = "duel-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "api",
    "cron",
    "dt-db",
    "dt-capsolver",
    "dt-logger",
    "dt-parser",
    "dt-scraper",
    "dt-seeder",
]

[tool.uv.workspace]
members = [
    "apps/api",
    "packages/dt-db",
    "packages/dt-logger",
    "packages/dt-parser",
    "packages/dt-scraper",
    "packages/dt-seeder",
    "apps/cron",
    "packages/dt-capsolver",
]

[tool.uv.sources]
api = { workspace = true }
dt-db = { workspace = true }
dt-logger = { workspace = true }
dt-parser = { workspace = true }
dt-scraper = { workspace = true }
dt-seeder = { workspace = true }
cron = { workspace = true }
dt-capsolver = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.4",
]

[tool.uv]
cache-dir = ".cache"

[tool.ruff.lint.isort]
known-first-party = ["dt_db", "dt_logger", "dt_parser", "dt_scraper", "dt_seeder", "dt_capsolver"]

[tool.ty.src]
exclude = [".cache", "**/tests"]
