/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrapeIndexRouteImport } from './routes/scrape/index'
import { Route as ScrapeBatchIdRouteImport } from './routes/scrape/$batch-id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapeIndexRoute = ScrapeIndexRouteImport.update({
  id: '/scrape/',
  path: '/scrape/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapeBatchIdRoute = ScrapeBatchIdRouteImport.update({
  id: '/scrape/$batch-id',
  path: '/scrape/$batch-id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scrape/$batch-id': typeof ScrapeBatchIdRoute
  '/scrape': typeof ScrapeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scrape/$batch-id': typeof ScrapeBatchIdRoute
  '/scrape': typeof ScrapeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scrape/$batch-id': typeof ScrapeBatchIdRoute
  '/scrape/': typeof ScrapeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scrape/$batch-id' | '/scrape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scrape/$batch-id' | '/scrape'
  id: '__root__' | '/' | '/scrape/$batch-id' | '/scrape/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScrapeBatchIdRoute: typeof ScrapeBatchIdRoute
  ScrapeIndexRoute: typeof ScrapeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrape/': {
      id: '/scrape/'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof ScrapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrape/$batch-id': {
      id: '/scrape/$batch-id'
      path: '/scrape/$batch-id'
      fullPath: '/scrape/$batch-id'
      preLoaderRoute: typeof ScrapeBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScrapeBatchIdRoute: ScrapeBatchIdRoute,
  ScrapeIndexRoute: ScrapeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
