/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as BatchIndexRouteImport } from './routes/batch/index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$player-id'
import { Route as BatchBatchIdRouteImport } from './routes/batch/$batch-id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchIndexRoute = BatchIndexRouteImport.update({
  id: '/batch/',
  path: '/batch/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$player-id',
  path: '/players/$player-id',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batch-id',
  path: '/batch/$batch-id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch/$batch-id': typeof BatchBatchIdRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/batch': typeof BatchIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch/$batch-id': typeof BatchBatchIdRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/batch': typeof BatchIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch/$batch-id': typeof BatchBatchIdRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/batch/': typeof BatchIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch/$batch-id'
    | '/players/$player-id'
    | '/batch'
    | '/players'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batch/$batch-id' | '/players/$player-id' | '/batch' | '/players'
  id:
    | '__root__'
    | '/'
    | '/batch/$batch-id'
    | '/players/$player-id'
    | '/batch/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchBatchIdRoute: typeof BatchBatchIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  BatchIndexRoute: typeof BatchIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/': {
      id: '/batch/'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$player-id': {
      id: '/players/$player-id'
      path: '/players/$player-id'
      fullPath: '/players/$player-id'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batch-id': {
      id: '/batch/$batch-id'
      path: '/batch/$batch-id'
      fullPath: '/batch/$batch-id'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchBatchIdRoute: BatchBatchIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  BatchIndexRoute: BatchIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
