[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.6.0",
    "db",
    "fastapi[standard]>=0.126.0",
    "httpx>=0.28.1",
    "logger",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "scraper",
    "slowapi>=0.1.9",
]

[tool.uv.sources]
logger = { workspace = true }
db = { workspace = true }
scraper = { workspace = true }


[tool.ty.environment]
python-version = "3.13"

[tool.ty.src]
include = ["app"]
